// Changes
// --------
// 14.08.2019 - Ersterstellung
// 




DEFINE

VAR
	FILTER_MaterialNo 	= FILTER 	(
						        	VALUES ( 'Material'[Materialcode] ),	        	
						        	// Helikopter
						        	('Material'[Materialcode] = "60" ) || ('Material'[Materialcode] = "61" ) ||
						        	('Material'[Materialcode] = "62" ) || ('Material'[Materialcode] = "63" ) ||
						        	('Material'[Materialcode] = "64" ) || ('Material'[Materialcode] = "65" ) ||
						        	('Material'[Materialcode] = "66" ) || ('Material'[Materialcode] = "67" ) ||
						        	('Material'[Materialcode] = "69" ) 
						        	)
						       
VAR
	FILTER_Basen		= FILTER 	('Basis',
									('Basis'[Basistyp]  = "Partner" && 'Basis'[Basis] = "AGLL") ||
									('Basis'[Basistyp]  = "Partner" && 'Basis'[Basis] = "AGLS") ||
									('Basis'[Basistyp]  = "Partner" && 'Basis'[Basis] = "EBGE") ||
									('Basis'[Basistyp]  = "Partner" && 'Basis'[Basis] = "HBES") ||
							    	('Basis'[Basistyp] 	= "EB16/17") 		||
									('Basis'[Basistyp] 	= "Mittelland") 	||
									('Basis'[Basistyp] 	= "Heli Rega H125") ||					
									('Basis'[Basistyp] 	= "Heli Rega IREOS")||					
									('Basis'[Basistyp] 	= "Gebirgsbasis")
							    	)

VAR
	FILTER_EinsatzArt	= FILTER 	(VALUES ( 'Einsatzart'[Einsatzart] ),
									(
									('Einsatzart'[Einsatzart] =  "Primäreinsätze" 		) 	|| 
									('Einsatzart'[Einsatzart] =  "Sekundäreinsätze" 	)	||
									('Einsatzart'[Einsatzart] =  "Spezielle Einsätze" 	)			        		
									)
									)

vAR 
	Var_FlugdauerTotal 	= CALCULATE([Flugdauer in min. Total]
							,FILTER	(DISTINCT(Einsatzdatum[CAL_DATE])
							 		 ,Einsatzdatum[CAL_DATE] = @Par_Einsatzdatum
								  	)
							,FILTER_EinsatzArt
						    ,FILTER_Basen
						    ,FILTER_MaterialNo
						    )
						       
VAR 
	Var_FlugdauerTotalHHMM = CALCULATE(
							 IF(ISBLANK(Var_FlugdauerTotal),BLANK(),CONCATENATE(CONCATENATE(ROUNDDOWN(Var_FlugdauerTotal/60,0),":"),IF(LEN(MOD(Var_FlugdauerTotal,60))=1,CONCATENATE("0",MOD(Var_FlugdauerTotal,60)),MOD(Var_FlugdauerTotal,60))))
							,FILTER	(DISTINCT(Einsatzdatum[CAL_DATE])
							 		 ,Einsatzdatum[CAL_DATE] = @Par_Einsatzdatum
								  	)
							,FILTER_EinsatzArt
						    ,FILTER_Basen
						    ,FILTER_MaterialNo
						    )


EVALUATE

ADDCOLUMNS(
	SUMMARIZECOLUMNS (
	     'Basis'[Basistyp]
	    ,'Basis'[Basis]
	    , FILTER	(DISTINCT(Einsatzdatum[CAL_DATE])
		 		 ,Einsatzdatum[CAL_DATE] = @Par_Einsatzdatum
			  	)
		,FILTER_EinsatzArt
	    ,FILTER_Basen
	    ,FILTER_MaterialNo
		,
	    "Primär"			, CALCULATE([Anzahl Einsätze durchgeführt],FILTER('Einsatzart','Einsatzart'[Einsatzart] =  "Primäreinsätze")),
	    "Sekundär"			, CALCULATE([Anzahl Einsätze durchgeführt],FILTER('Einsatzart','Einsatzart'[Einsatzart] =  "Sekundäreinsätze" )),
	    "Nacht"				, [Anzahl Nachteinsätze Total],
	    "Abgebrochen"		, [Anzahl Einsätze abgebrochen],
		"Total"				, [Anzahl Einsätze Total],	    
	    "Flugdauer in HH:MM", [Flugdauer in HH:MM]

	)
, "FlugdauerTotal HHMM"						, Var_FlugdauerTotalHHMM

)


<Parameters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="urn:schemas-microsoft-com:xml-analysis">  <Parameter>
    <Name>Par_Einsatzdatum</Name>
    <Value xsi:type="xsd: string">2019-07-30</Value>
  </Parameter>
</Parameters>